/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
  java
}

repositories {
  mavenLocal()
  mavenCentral()
}
description = "core"

val testsJar by tasks.registering(Jar::class) {
  archiveClassifier.set("tests")
  from(sourceSets["test"].output)
}

val instrumentedJars by configurations.creating {
  isCanBeConsumed = true
  isCanBeResolved = false
}

java {
  withSourcesJar()
  withJavadocJar()
}

artifacts {
  add("instrumentedJars", testsJar)
}

dependencies {
  val flinkVersion = "1.12.4"
  implementation("org.apache.flink:flink-avro:$flinkVersion")
  implementation("org.apache.flink:flink-connector-kafka_2.11:$flinkVersion")
  implementation("com.google.cloud:google-cloud-storage:1.113.8")

  implementation("org.apache.flink:flink-test-utils_2.11:$flinkVersion")
}

tasks.test {
  useJUnitPlatform()
}

publishing {
  publications {
    create<MavenPublication>("mavenJava") {
      groupId = project.group.toString()
      artifactId = project.name
      version = project.version.toString()
      from(components["java"])
      pom {
        name.set(project.name)
        description.set("A stream library for batch and realtime data processing")
        url.set("https://github.com/airwallex/AirSkiff")

        signing {
          sign(publishing.publications)
          sign(configurations.archives.get())
        }

        licenses {
          license {
            name.set("The MIT License")
            url.set("https://opensource.org/licenses/MIT")
          }
        }
        developers {
          developer {
            id.set("tzhu-airwallex")
            name.set("Tianshi Zhu")
            email.set("tzhu@airwallex.com")
          }
        }
        scm {
          connection.set("scm:svn:https://github.com/airwallex/AirSkiff.git")
          developerConnection.set("scm:svn:https://github.com/airwallex/AirSkiff.git")
          url.set("https://github.com/airwallex/AirSkiff.git")
        }
      }
    }
  }
}
